export const TAG_SKILL_MAP: Record<string, string[]> = {
  'fundamentos': ['control_basics', 'credit_basics'],
  'habitos': ['control_basics', 'auto_saving', 'debt_plan_30d'],
  'presupuesto': ['budget_3_buckets', 'spending_leaks'],
  'ahorro': ['auto_saving', 'emergency_fund'],
  'fondo': ['emergency_fund'],
  'score': ['credit_score'],
  'historial': ['credit_score'],
  'tarjeta': ['min_payment_trap'],
  'deuda': ['snowball_avalanche', 'debt_plan_30d'],
  'tasa': ['rate_compare'],
  'comparacion': ['rate_compare'],
  'fraude': ['fraud_basics', 'identity_protection'],
  'seguridad': ['identity_protection'],
  'proteccion': ['identity_protection'],
  'estrategia': ['snowball_avalanche'],
  'plan_30d': ['debt_plan_30d'],
  'credito': ['credit_basics'],
  'decisiones': ['control_basics'],
  'coach': ['control_basics'],
  'sistema': ['auto_saving', 'debt_plan_30d'],
};
